apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-job
spec:
  template:
    metadata:
      name: db-migration-job
    spec:
      containers:
        - name: db-migrations
          image: db-migrations:latest
          imagePullPolicy: Never
          env:
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: db-cluster-app
                  key: username
                  optional: false
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-cluster-app
                  key: password
                  optional: false
      restartPolicy: Never
  backoffLimit: 2