apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: qa-ui-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qa-ui-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50